# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_bookinfo_heroinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='areas',
            fields=[
                ('aid', models.IntegerField(primary_key=True, serialize=False)),
                ('atitle', models.CharField(max_length=20)),
                ('pid', models.IntegerField(null=True)),
            ],
        ),
    ]
