# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_bookinfo_heroinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroinfo',
            name='hero_hometown',
            field=models.CharField(default='金庸小说', max_length=70),
        ),
    ]
