# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_areas'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyPic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic_desc', models.CharField(max_length=200)),
                ('pic_name', models.ImageField(upload_to='images')),
            ],
        ),
    ]
