# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 11:31
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_mypic'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=100)),
                ('news_content', tinymce.models.HTMLField()),
            ],
        ),
    ]
